# Generated by Django 3.2.15 on 2023-01-06 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_remove_book_authors_imgs'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibraryClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество')),
                ('passport_number', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Номер паспорта')),
                ('date_of_bitrh', models.DateField(verbose_name='Дата рождения')),
                ('e_mail', models.EmailField(max_length=254, unique=True, verbose_name='Адрес электроной почты')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='OwnedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.libraryclient', verbose_name='Клиент')),
                ('owneded_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.book', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Выданная книга',
                'verbose_name_plural': 'Выданные книги',
            },
        ),
        migrations.CreateModel(
            name='ClientAdress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cтрана')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='Город')),
                ('home_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер дома')),
                ('apartment_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер квартиры')),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='client.libraryclient', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
    ]
