# Generated by Django 3.2.15 on 2023-01-05 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('russian_name', models.CharField(max_length=255, verbose_name='Русское название книги')),
                ('original_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Оригинальное название книги')),
                ('price', models.PositiveBigIntegerField(verbose_name='Цена')),
                ('book_count', models.PositiveIntegerField(verbose_name='Количество экземпляров')),
                ('cover_img', models.FileField(upload_to='media/book/%Y/%m/%d/')),
                ('one_use_day_price', models.PositiveBigIntegerField(verbose_name='Цена за 1 день')),
                ('make_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год создания')),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('page_count', models.IntegerField(blank=True, null=True, verbose_name='Количество страниц')),
                ('authors', models.ManyToManyField(to='main.Authors', verbose_name='Авторы')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['-russian_name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='BookAuthorsFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autors_img', models.FileField(blank=True, null=True, upload_to='media/author/%Y/%m/%d/', verbose_name='Фото автора')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='main.authors', verbose_name='Автор')),
                ('main_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.book', verbose_name='Книга')),
            ],
            options={
                'verbose_name': 'Фото автора',
                'verbose_name_plural': 'Фото атворов',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='authors_imgs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.bookauthorsfoto', verbose_name='Фото авторов'),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(to='main.Genre', verbose_name='Жанр'),
        ),
    ]
